tvbd_diff: Add `write_log` option
Irrational-Encoding-Wizardry/lvsfunc pull request #40
Opened 2020-12-21 19:34 UTC by DeadNews

For example:
```python
frames = [
    3093, 3094, 3095, 3096, 3097, 3098, 3099, 3100, 3101, 3102, 3103, 3104, 3105, 3106, 3107, 3108, 3109, 3110, 3111,
    3112, 3113, 3114, 3115, 3116, 3117, 3118, 3119, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127, 3128, 3129, 3130,
    3131, 3132, 3133, 3134, 3135, 3136, 3137, 3138, 3139, 3140, 3141, 3142, 3143, 3144, 3145, 3146, 3147, 3148, 3149,
    3150, 3151, 3152, 3153, 3154, 3155, 3156, 3157, 3158, 3159, 3160, 3161, 3162, 3163, 3164, 3165, 3166, 3167, 3168,
    3169, 3170, 3171, 3172, 3173, 3174, 3175, 34645, 34646, 34647, 34648, 34649, 34650, 34651, 34652, 34653, 34654,
    34655, 34656, 34657, 34658, 34659, 34660, 34661, 34662, 34663, 34664, 34665, 34666, 34667, 34668, 34669, 34670,
    34671, 34672, 34673, 34674, 34675, 34676, 34677, 34678, 34679, 34680, 34681, 34682, 34683, 34684, 34685, 34686,
    34687, 34688, 34689, 34690, 34691, 34692
]

write_log = True
#ep_name = 'e1'
ep_name = 'e2'

if write_log:
    from itertools import groupby, count

    def intervals(frames: list) -> list:
        out = []
        counter = count()

        for key, group in groupby(frames, key=lambda x: x - next(counter)):
            block = tuple(group)
            out.append((block[0], block[-1]))
        return out

    with open('./diff.log', 'a') as log:
        if ep_name:
            log.write(f"{ep_name}: ")
        log.write(f"{str(intervals(frames))} \n\n")
```
will create `./diff.log` that contains:
```
e1: [(3093, 3175), (34645, 34692)] 

e2: [(3093, 3175), (34645, 34692)] 

```

2020-12-21 19:57 UTC, heicrd requested changes

2020-12-21 19:57 UTC, heicrd commented on lvsfunc/comparison.py
> +              write_log: bool = False,
i feel like we should just pass a file handle (maybe `typing.Optional[typing.TextIO]`?), then the caller can prepend/append any extra data they want (like episode name) as well as use a specific path

2020-12-21 19:57 UTC, heicrd commented on lvsfunc/comparison.py
> +        from itertools import groupby, count
itertools is pretty standard so there's not really a reason to defer this import rather than putting it at the top of the py file

2020-12-21 19:57 UTC, heicrd commented on lvsfunc/comparison.py
> +        def intervals(frames: list) -> list:
no real reason to nest this this deeply, can just make it a top-level function like `_get_diff_intervals`
also the correct typehint for `frames` should be `typing.List[int]` and it returns `typing.List[typing.Tuple[int, int]]`

2020-12-21 19:57 UTC, heicrd commented on lvsfunc/comparison.py
> +            if ep_name:
as per above, this can be handled by the caller

2020-12-21 19:57 UTC, heicrd commented on lvsfunc/comparison.py
> +            out = []
probably needs typehinted

2020-12-21 19:57 UTC, heicrd commented on lvsfunc/comparison.py
> +            for key, group in groupby(frames, key=lambda x: x - next(counter)):
you can use `_` for `key` as a placeholder to make linters happier since it's unused

2020-12-27 17:09 UTC, DeadNews commented
On second thought, why not just add the ability to return `frames` too?
```python
return frames, Stack((tvbd_stack, diff), direction=Direction.VERTICAL).clip
```
That would be enough for me.

2020-12-31 22:59 UTC, heicrd commented
i think returning the frame list would be a good option

2021-01-04 00:29 UTC, closed without merging